### ISSUE TITLE
Question about indeterminate

### ISSUE THREAD

**Issue by mrjjwright** [danielearwicker/bidi-mobx#14]
Curious as to the purpose of the  Lambda indeterminate logic [here](https://github.com/danielearwicker/bidi-mobx/blob/master/src/components/CheckBox.tsx#L16).   Do you mind explaining a bit when you have a chance?

**Comment by danielearwicker** [comment]
Sure, it's actually a couple of cans of worms, but it turns out okay and may be interesting. Sorry if any of this is too detailed but it's kind of a fun instructive mini blog post.

Checkboxes have three visual states: unchecked, checked and indeterminate (neither checked nor unchecked). The third state is useful for "Select all", which is checked when all other items are checked, etc. and needs a way to represent "some are checked, some are unchecked". There's [an example here](https://danielearwicker.github.io/bidi-mobx/) called 'Music Library' that applies the logic recursively.

Can of worms 1: The DOM is vague and inconsistently implemented. The API suggests indeterminacy is an orthogonal state, i.e. you can set it independently without affecting `checked`, so a checkbox can be in four states, although two of them look the same to the user. Whether this is true seems to depend on the browser, and seems pretty useless anyway.

To simplify, I use `undefined` to mean indeterminate, allowing three states to be represented by:

* `false` - unchecked
* `true` - checked
* `undefined` - indeterminate

And so a simple two-state checkbox can just use `boolean` and ignore all this stuff. The `value` prop of `CheckBox` is declared as:

```ts
value: BoxedValue<boolean | undefined>
```

But this is not precise, because while the `get` method may return `undefined` the `set` will never receive `undefined` (there is no UI for the user to request indeterminate state: they can only toggle into checked or unchecked). So really it should written out long hand as:

```ts
value: {
    get(): boolean | undefined;
    set(value: boolean): void;
}
```

But it's close enough in TS because of "bivariance", which means you can pass a `BoxedValue<boolean>` anyway:

```ts
const blah = observable.box(true);
return <CheckBox value={blah} />; 
```

Which is can of worms 2: we've caught the type system napping. That's unsound because `blah.set` only accepts `boolean` and yet the `value` prop claims it may pass `undefined`. But TS (riskily) is satisfied if the parameters are related (sub-type/super-type) *in either direction*. `boolean` is a subtype of `boolean|undefined`, because types are sets of values, same as how [programming languages are sets of programs](http://danielearwicker.github.io/TypeScript_is_not_really_a_superset_of_JavaScript_and_that_is_a_Good_Thing.html). `boolean` is the set `{ true, false }` which is a subset of `{ true, false, undefined }`.

For soundness, TS ought to check that `blah.set` accepts a super-type (a type *at least* capable of representing what might be passed).

But it's actually fine here because `CheckBox` never passes `undefined` to `set` anyway.

If we changed the declaration of `value` to the more precise version, that would also fit both `BoxedValue<boolean>` and `BoxedValue<boolean|undefined>`, even if TS was enhanced to have a "super sound" mode where it checked function parameter types are contravariant and return types are covaraint.

`BoxedValue<boolean>` has `get(): boolean` which is covariant with `get(): boolean|undefined`, and it has `set(v: boolean): void` which exactly matches.

`BoxedValue<boolean|undefined>` has `get(): boolean|undefined` which exactly matches, and it has `set(v: boolean|undefined): void` which is contravariant with `set(v: boolean)`.

So we might need to do that one day. But right now it's a moot point!

**Comment by mrjjwright** [comment]
Fascinating, thanks!!
