### ISSUE TITLE
Creating fields on existing objects

### ISSUE THREAD

**Issue by mrjjwright** [danielearwicker/bidi-mobx#5]
Let's say you have an existing object

`class Existing {
@observable x:number;
}
`

and at run time you want to add a field/adaptor to it instead of at creation time.  With bidi currently the way it it is, I need to define something like this instead of the above:

`class Existing {
@observable x = field(numberAsString(0)).create(0, "x");
}
`

I want to keep things like the first way because I don't want to expose Bidi to the rest of my architecture so that not every part, except those in the editor/input system, have to know about the underlying Bidi `model` object and that you are dealing with an bidi/adaptor.  The underlying state of my project are just simple objects with mobx observables and it would be nice to keep them that way.  

It would be nice if you could call something like:

`field(numberAsString(0)).fromBox(box(existingObject).name).create(0, "x")`

Also the `boxm` approach handle this nicely as you can just call `box(existingObject).x` and get going; downside is there are no easy way to add and chain adaptors and validators in this approach, unless I roll something myself.  I tried to figure out if I could do this with bidi-mobx, namely supply an existing object but it seems the api assumes that property is aways initialized to a bidi field/adaptor and that bidi itself will own the underlying `@observable`.

(I noticed that this project only uses a bit of the spirit of boxm and doesn't really use `box` itself except in a few cases in the demos, unless I am wrong, although it does re-export the `box` call on top of mobx atoms.)

Again, a cool power of `boxm` IMHO is working with existing underlying objects, creating these little derived boxes for a special reason such as input, without touching the underlying object.

**Comment by danielearwicker** [comment]
Ironically in an earlier iteration of the API the model was indeed a `BoxedValue`! [In this change](https://github.com/danielearwicker/bidi-mobx/commit/d56f0e0b73e25c746e62e00f32de3fe0f6563a51) I removed a class called `ConversionModel` - `parsed` is the model and `formatted` is the view.

I removed it to simplify things as it could always be put back if needed.

I totally agree with keeping models simple, and just "dressing them" in a view model, so this makes a lot of sense.

**Comment by mrjjwright** [comment]
I think it would be a better evolution of the core ideas of `boxm` and really flexible if you could go back to that design somehow, perhaps merging it with the best ideas since added and now a part of bidi.  Just my 2 cents.  I almost used [formstate](https://formstate.github.io/#/) but it requires again too much impact to the existing object/observable model, just a bit too much boilerplate.  With mobx, as you know, you really want to stay minimal and close to the metal, when working with core state.  Computeds and derivation are no big deal but I like to keep my core model really tight.  This lib and `boxm` are two of the only libs I have seen that try to work with core observables and respect their atomicity.  

That being said, it's not terribly hard for me to roll my own solution with `boxm`,  Mobx `atoms` and especially that really nice custom `boxer` function you made!  I think I understand it pretty well now and if you want to keep this lib really simple, I totally understand.

**Comment by mrjjwright** [comment]
Ok I was able to start down the road of solving my use case of needing some simple adaptors and validation with this simple code.  Let me know if see any big red flags. HOFs to the rescue.

```es6
export const createBox = <T>(adaptor?:(val: SimpleValue) => SimpleValue) : <T>(obj: T) => BoxedObject<T> => {
  let theFunc = (obj, key) => {
    invariant(isObservable(obj, key) || isComputed(obj, key), "Must supply observable or computed");
    const atom = extras.getAtom(obj, key) as any as BoxedValue<any>;
    invariant(atom != null, "Unable to create atom for key" + key);
    if (adaptor) {
      let wrappedAtom = {
        get(): T {
          return atom.get()
        },
        set(v: T):void{
          atom.set(adaptor(v));
        }
      }
      return wrappedAtom;
    }
    return atom;
  }
  return boxer(theFunc);
};

let numberToStringBox = createBox((val:SimpleValue) => {
  return Number(val);
});
```

**Comment by danielearwicker** [comment]
Take a look at 0.17.2. `FieldBuilder` has a new `use` function that is an alternative to `create`. Instead of an initial value, it takes a `BoxedValue<Model>`, which provides the underlying model storage for the field's value.

[There's a demo too](https://danielearwicker.github.io/bidi-mobx/), [source](https://github.com/danielearwicker/bidi-mobx/blob/master/kitchenSink/TwinMultiplier.tsx).

The `Model` just has the data (including derived data) and also a computed that tells you if it's an  `invalid` combination of values.

The `ViewModel` is explicitly a separate thing from `Model` (which is pure "textbook" MobX), and it wraps `a` and `b` with the `use` method.

Then as a demo I create two identical instances of the UI, so you can see that they are both editing the same underlying model. Change one of them and the other also changes.

I'm going to keep tweaking to find ways to reduce noise and take better advantage of type inference.

**Comment by mrjjwright** [comment]
Omg, Christmas just arrived.  `Unboxing now...`. 💯

**Comment by mrjjwright** [comment]
[Love](https://github.com/danielearwicker/bidi-mobx/blob/master/kitchenSink/TwinMultiplier.tsx#L44)

So clean.

**Comment by mrjjwright** [comment]
Thank-you, thank-you, thank-you.  Off to go play with it.

**Comment by danielearwicker** [comment]
Check again! I've shrunk down the `TwinMultiplier` example by about 25% of lines and eliminated lots of type declarations (in fact there are now only 2 in the whole example).

The key addition is a tiny new API called Project/Render. You have to provide two pieces, pure functions:

* `project`: a function that creates a view-model from a model (the "projection")
* `render`: simply a stateless React component (as usual, a function from props to JSX)

```ts
import { project } from "bidi-mobx";

const MyComponent = project(model => { whatever... }).render(props => <whatever/>);
```

Why are these in two pieces? Because `render` has to happen a lot more often than `project`. The view-model has to persist across renders.

Splitting it into a builder pattern (instead of a single function that takes two args) helps with type inference. From the main example:

```ts
const Multiplier = project((model: Model) => {

    const factor = field(numberLimits(1, 10)).also(numberAsString(2));

    const a = factor.use(box(model).a, "A"),
          b = factor.use(box(model).b, "B"),
          validation = rules([a, b, rule(() => model.invalid)]);

    return { a, b, validation };

}).render<{ background: string }>(props => { 
    
    const { a, b, validation } = props.view;
    const { product } = props.model;

    return (
        <div style={{ background: props.background }}>
            <div><label>A = <TextInput value={a}/></label></div>
            <div><label>B = <TextInput value={b}/></label></div>
            <div>Product ({a.model} * {b.model}) = {product.toFixed(2)}</div>
            <hr/>
            <RuleBullets rule={validation} />
        </div>
    );
});
```

See how `render` can take a type argument (optional). This is where you say what props you need, but you don't have to include `view` or `model` - they will be mixed in for you. So here I ask for a background colour.

The returned component only needs `model` and `background` to be supplied. So it's a fully self-contained component for editing a `Model` that maintains its own state, but you write it fully functionally. The `project` piece is a pure function from model to view-model. The `render` piece is a pure function from `props` to JSX.

**Comment by mrjjwright** [comment]
Holy crap, I like this a lot better, so much smaller, and I love the rendering to JSX.  This is going to be a key piece of my editor.  I will play with this more in a couple hours.

**Comment by mrjjwright** [comment]
This is so freaking cool.  I need these exact kind of self contained components in my visual app builder.

**Comment by mrjjwright** [comment]
This is proving to be an extremely useful pattern for composing combinations of view models and rendered components dynamically while keeping everything connected to state.   Awesome refactor and insight today.

**Comment by mrjjwright** [comment]
This MVVM pattern is rad.  I now have some basic `types` and `data`, some `projections`, and a `model` which calculates the different `projections` as `@computeds` based on the state of its `@observables`.  My app.tsx is just a shell which displays the larger projections in major areas.   The data flow is very easy to reason about and I can compose different combos of view models and renders as so from `projections.tsx` (I have tons more than these already):

```es6

export function valuesForType(model:{type:Type}):Value[] {
    return model.type.items.map(field => {
      let newItem:Value =  {
          ...createItem(field.name), 
        kind: ItemKind.Value,
        editMode:true,
        inputKind: InputKind.Dropdown,
        possibleNames: fieldTypeDisplayNames,
        possibleValues: enumValues(InputKind),
        auxText: "text",
        boxValue: Bidi.field(Bidi.numberAsString()).use(Bidi.box(field).fieldKind, field.name)
      } 
      return newItem;
  }) 
}

const simpleListRender = (props:SimpleListProps & SelectionProps) =>  {
    const items = props.view ? props.view : [];
    let theItems = items.map(item => {
    return <ListItemView key={item.id} item={item} isSelected={item == props.selectedItem} 
        onSelect={props.onSelect}/>
    })
    return (
        <UI.ListWrapper>
            {theItems}
        </UI.ListWrapper>
    );
}

export const TypeValueList = Bidi.project(valuesForType).render(simpleListRender)
export const DataValueList = Bidi.project(valuesForData).render(simpleListRender)

``` 

This is really a big and different take on MVVM because it's very functional, automatic, fit's into the observable/derivation graph that mobx provides, and is composable.  Usually I write some ugly version of `if/then` handlers in massive JSX render calls.  This replaces all the code with clean and composable snippets, starting with `observables` and `computeds` on the  Mobx model, down through the bidi powered view models, and to reusable functional renders...and back again!  At the leaf level, it's also really a great use of functional components.

You did something big today! :1st_place_medal: 

<img width="384" alt="screen shot 2017-01-22 at 11 55 13 pm" src="https://cloud.githubusercontent.com/assets/4343/22194258/67c0511e-e0fe-11e6-8a27-c3537e0f16bb.png">

**Comment by danielearwicker** [comment]
Thanks very much! I somehow missed this comment until now.
