### ISSUE TITLE
Project function isn't in derivation graph

### ISSUE THREAD

**Issue by mrjjwright** [danielearwicker/bidi-mobx#7]
Although the returned component from `render` is wrapped in an `observer`, calls like [this](https://github.com/danielearwicker/bidi-mobx/blob/master/src/project.ts#L25)  to `projection` aren't tracked in the mobx observable graph because they are called outside of render.  That means the view model isn't re-projected from the underlying mobx model when it changes and hence renders that depend on various properties in the view model get out of sync.  Is there an easy way to make that happen?  I assume just move at least one of those lines down to the render.

**Comment by danielearwicker** [comment]
Are these properties in the view model just plain values rather than observables themselves?

Suppose the view contains field A (observable with its own extra state) and plain value B. If B changes and we rebuild the view, then the extra editing state of A will be lost.

I can presumably make this change anyway though, I'll have a look later.

**Comment by mrjjwright** [comment]
Actually, I just tried moving the call to `projection` inside the render (in my own copy of that function) and that just causes the component to get re-rendered in a bad way.  E.g. as the user types in a text input, it re-creates the component on every keystroke.  I naively didn't understand that you were returning a new component every-time the `projection` it is called.

To answer your above question: these are just simple plain values in the view state.   I was assuming that since the component can edit the mobx model, the model can change, and new view state objects can be derived per the mobx way.  I think the only way to make this work correctly is to have all the view states be `computeds` on the original model, since that is what they really are: values derived from the model.  As it stands now, you get a one time derivation of a view state object which returns the bidi-observables.  Obviously changing those causes rerenders on the returned component as well as passing it new `ExtraProps` but you can never re-derive any view state objects.

**Comment by mrjjwright** [comment]
Actually I take back what I said above:  the only solution is NOT to use computed.  Even with `mobx-react`, `observers` run as a `reaction` that causes a side effect and hence logically you could see the `re-projection` of the view model as the same.  But I may have the answer, the `componentWillReact` hook!  Testing it out now.

**Comment by mrjjwright** [comment]
Nah, that's not it.  It's the children `<TextInput/>` components that are updating, not the parent component that bidi creates.  There is no tracked data inside the component that would cause it to run.  Trying a simple autorun.

**Comment by danielearwicker** [comment]
I think you might be working harder than you need to here, unless I'm misunderstanding you - maybe you're using `project` for a different use case than I envisaged.

> To answer your above question: these are just simple plain values in the view state. I was assuming that since the component can edit the mobx model, the model can change, and new view state objects can be derived per the mobx way. 

The idea of the view state is that it maintains the extra state associated with the UI mechanisms (whatever they might be) and only flushes changes down to the underlying model when the view state maps to a valid model state.

The idea of the `use` method I added yesterday is that your fields are indeed tied to a property of an external model. If the underlying model changes, that field is recomputed. So in [Twin Multiplier](http://danielearwicker.github.io/bidi-mobx) if you change an input on the left, it updates on the right, because both are derived from the same model. But if you type a non-digit character and get a validation error, nothing is pushed down to the model until you fix it.

> I think the only way to make this work correctly is to have all the view states be computeds on the original model, since that is what they really are: values derived from the model. As it stands now, you get a one time derivation of a view state object which returns the bidi-observables. 

That is correct.  A fields is nothing more than a combination of `computed`s layered over the underlying model value, with the added ability to maintain extra state purely to support the UI, and allow the UI to be in an invalid state (or to be in one of many view states that map to the same model state).

The fields (and any other plain computeds) in view state keep *themselves* up-to-date with the underlying model property that they are derived from.

This is no different from MobX generally. If you copy a plain value out of an observable and store it as a plain value, you've broken the link with the source. If you don't want to do that, and the flow is only one-way, just use `computed`. If it's two-way and you'll be doing conversions which "widen" or "narrow" the data type depending on the direction, then that's what `field` is all about.

> Obviously changing those causes rerenders on the returned component as well as passing it new ExtraProps but you can never re-derive any view state objects.

Do have another look at `TwinMultiplier`. All the things in the view state are either `computed` from the model (so stay consistent with it) or are declared as fields (which are like two-way computed). This means they are self-maintaining.

One way to clarify this is to note that when you edit an `@observable` value in the model, you haven't changed the model at all. It is still an object that contains the same observable wrapper. Observables are a bridge for immutable objects to refer to mutable values.

**Comment by mrjjwright** [comment]
Duh: I just need to create a boxed property inside the view model for every property I want to keep up to date in the view and then decide if it's 1 or 2 way.   Now I remember you doing that here and there in the examples.   You are so right.   Once again `boxm` to the rescue.  Sorry for wasting your time on this one and thanks so much for the help.

**Comment by mrjjwright** [comment]
It's funny that this behavior is at the core of your library and I wasn't grasping it.  Like I just now got the name was short for bi-directional.  Sigh, as usual, the easiest and the most obvious things are the hardest for me to see.

**Comment by danielearwicker** [comment]
No problem, this is all useful because it highlights things that need better explanation. I haven't documented `project` yet but this is going to make it easier to write.

The thing with MobX (and libraries built on it like this) is that it can be difficult to realise how easy it is! :smile: From habit we assume that there are various edge cases we'll need to worry about, but usually... nope.

**Comment by mrjjwright** [comment]
Hmm, so calling a `<div>{viewModelBoxedValue.get()}</div>` in `render` at the highest level above the rest of the form control causes all the children to be recreated and I lose focus inside `<TextInput/>` components after every typed char.  Sigh, not sure what I am doing wrong.  I am going to get some sleep and I am sure I will figure it out.  Good news is the ownerComponent of the render does re-render so everything seems in sync but something is still off.  This was after I reverted back to your version of `project`.

**Comment by mrjjwright** [comment]
Ok, while `project` really clarified for me what a view model in bidi can, could, and should be, I am not sure I will actually use it, and instead just favor composing view models and passing them to components as a prop called `viewModel`.   The reason is because HOCs that depend on the component lifecycle make my code just a bit more difficult to reason about.  The only one that I really depend on right now is `mobx-react's observer`, a side effect with React edge cases all tested for, and I think i want to keep it at that.  Also this allows my view models to optionally be `@computed` on the original model, which is nice in certain cases.  So awesome little builder mechanism but I think I will pass for now.  What I won't pass on is this MVVM idea you have going here.  I now have re-usable view models with these powerful 1 and 2 way binding mechanism to and from the dom/render, all thanks to bidi!

**Comment by danielearwicker** [comment]
Sure, it's really just a shorthand for a class that maps construction and `componentWillReceiveProps` to the same thing. Also it does type inference better than a class. That's really all it is.

**Comment by mrjjwright** [comment]
Am I just being thrown off by the flickering render in my `<TextInput/>`?  Obviously those controls are being recreated for some reason.  Let me debug the root cause for that, might be something I am doing/missing.   Because better type inference sounds awesome and I do like how a component can be created that represents a combination of a particular view model and render.

**Comment by danielearwicker** [comment]
I should write something longer on this topic but basically if one little atom of data (boxed in an observable) changes, and it is represented by a component, then only its component should re-render. The parent has no need to.

**Comment by mrjjwright** [comment]
Oh I totally agree.  I am leaving out an important detail, so sorry!  In this case, the atom of data is rendered both in the parent render and in the child <TextInput/>.

So 
```es6

render(props: {view: boxedValue}) {
     return (
      <div>
        <h1>{props.view.boxedValue.get()}</h1
        <TextInput value={props.view.boxedValue}/>
      </div>
      )
}
```

**Comment by mrjjwright** [comment]
I am doing something stupid, not sure what but I just tested the above scenario out in some other sample code and it worked fine in general, so it must be something deep within the specifics of my app.  So I am changing my mind, I will keep `project` pattern because it's useful, and I do notice the really good type inference.  But I will use more open-ended patterns as needed.  Once again, you rock!

**Comment by mrjjwright** [comment]
I got it working by re-writing it from scratch, not sure what I was doing but who cares, sorry for the trouble!

**Comment by mrjjwright** [comment]
I was making the most rookie of React mistakes, not setting a key on a React list properly.  Because of the architectural changes we are making, I got sent down a rabbit trail.

**Comment by danielearwicker** [comment]
Ok thanks for confirming!
